"""
This type stub file was generated by pyright.
"""

import asyncio
from typing import TYPE_CHECKING

from . import public

"""Utilities for writing and reading length-prefix framed messages.
Using length-prefixed framing makes it easier for the reader to determine the
boundaries of each message before passing it to msgspec to be decoded.
"""
if TYPE_CHECKING: ...

@public
async def prefixed_send(stream: asyncio.StreamWriter, buffer: bytes) -> None:
    """Write a length-prefixed buffer to the stream"""
    ...

@public
async def prefixed_recv(stream: asyncio.StreamReader) -> bytes:
    """Read a length-prefixed buffer from the stream"""
    ...
