"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, NoReturn, Optional, Tuple, Type, Union

from . import public

"""Utility functions for while loops"""

@public
def while_raised(
    exc_types: Tuple[Type[Exception]],
    target: Callable[..., Any],
    /,
    *args: Any,
    implicit_break: bool = ...,
) -> Union[Optional[Any], NoReturn]:
    """Repeats a target function while suppressing exceptions provided.
    This is a convenience wrapper around :py:func:`contextlib.suppress`.
    :param exc_types: The exception types to suppress.
    :type  exc_types: Tuple[Type[Exception]]
    :param target: The function to repeat.
    :type  target: Callable
    :param implicit_break: Whether to implicitly break out of the loop.
    :type  implicit_break: bool, defaults to True
    :return: The return value of the target function.
    """
    ...
