"""
This type stub file was generated by pyright.
"""

from typing import Set

from . import public

"""Sequence manipulation."""

@public
def chr_union(*args: int) -> Set[str]:
    """Wraps an asynchronous sequence of int ranges or ints into a set of str
    :return: a set of chr()
       # 1. range(start=args[0], stop=args[1])
          * OR
       # 2. chr(arg[n] if type(arg[n])==int) | chr_union(arg[:2])
    :raises: TypeError
        if not a sequence of start,stop pairs and ints, an int, or a start, stop pair
    """
    ...
