"""
This type stub file was generated by pyright.
"""

from typing import Annotated, Any, Callable, Optional, Tuple
from . import public

"""Utility for tail call optimization."""
TAIL_CALL: Tuple[()] = ...

@public
def async_tail_call(
    active: bool = ...,
) -> Annotated[Callable[..., Any], Annotated[Optional[Tuple[()]], '@tail_call()']]:
    """Async tail_call decorator.
    :param active: Whether to activate async tail call optimization.
    """
    ...
